# Generated by Django 6.0.6 on 2026-06-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelloWorldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='hello-world-images/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
            ],
        ),
    ]
